ENABLE_CHANGE_GUILD: false
ENABLE_NO_GUILD: false
ENABLE_DEFAULT_GUILD: false
ENABLE_FRIENDLY_FIRE_PVP: false
ENABLE_BASE_ON_DEATH: false
ENABLE_GUILD_PROTECTION_BARRIER: false
ENABLE_GUILD_PROTECTION_BARRIER_VOID: false
ENABLE_ENEMY_ENTER_PROTECTION_BARRIER: false
ENABLE_DAMAGE_ANIMATION_ON_ZERO: false
ENABLE_CHAT_COLOR: false
ENABLE_PLAYER_GUILD_PREFIX: false
ENABLE_PLAYER_LISTNAME_COLOR: false
ENABLE_PLAYER_LISTNAME_GUILD: false
ENABLE_GUILD_CHAT_FORMAT: false
ENABLE_GUILD_JOIN_PERMISSIONS: false
ENABLE_RESTRICTIONS: false
ENABLE_PICKUP_RESTRICTIONS: false
ENABLE_GUILD_NAME_ON_BROADCAST: false
SET_PROTECTION_BARRIER: 0
SET_BASE_TP_DELAY: 0
SET_CHAT_PREFIX: ''
SET_CHAT_SUFFIX: ''
SET_GUILDS_BROADCAST_COLOR: ''
SET_DEFAULT_GUILD: ''
SET_CHANGE_GUILD_TIME: 0
SET_PROTECTION_BARRIER_VOID: 0
